name: Build Flutter App

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_android:
    name: Gerar Android (APK)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter create --project-name diario_obra_mvp --org br.com.embraurb .
      
      # FIX 1: Forçar a versão mínima do Android para o Isar funcionar
      - run: sed -i 's/flutter.minSdkVersion/21/g' android/app/build.gradle
      
      # FIX 2: Desativar o Lint chato que trava o build do APK
      - run: echo -e "\nandroid {\n    lintOptions {\n        checkReleaseBuilds false\n        abortOnError false\n    }\n}" >> android/app/build.gradle
      
      - run: flutter pub get
      - run: dart run build_runner build --delete-conflicting-outputs
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build_web:
    name: Gerar Versão Web (PWA)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter create --project-name diario_obra_mvp --org br.com.embraurb .
      - run: flutter pub get
      - run: dart run build_runner build --delete-conflicting-outputs
      - run: flutter build web --release --base-href "/diario-obra-app/"
      - uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  deploy_web:
    name: Publicar na Internet
    needs: build_web
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
