name: Build Flutter App

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build_android:
    name: Gerar Android (APK)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Create Flutter platform files
        run: flutter create --project-name diario_obra_mvp --org br.com.embraurb --platforms=android .

      - name: Install dependencies
        run: flutter pub get

      - name: Generate Isar code
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk
